## GitHub Action for generating a contribution graph with a snake eating your contributions.

# name: Generate Contribution Snake

# on:
#   schedule:
#     - cron: "0 0 * * *"  # Runs daily at midnight (UTC)
#   workflow_dispatch:  # Allows manual triggering

# jobs:
#   generate:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     steps:
#       - name: Generate Contribution Snake
#         uses: Platane/snk@v2
#         with:
#           github_user_name: luoping1004
#           outputs: |
#             dist/github-contribution-grid-snake.svg
#             dist/github-contribution-grid-snake-dark.svg?palette=github-dark
#       - name: Upload Contribution Snake Artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: contribution-snake
#           path: dist/github-contribution-grid-snake.svg

#       - name: Run GitHub Metrics
#         uses: lowlighter/metrics@latest
#         with:
#           token: ${{ secrets.GH_PAT }}



name: Update Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: luoping1004
          svg_file_path: ./github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: Debug token
        run: |
          echo "Token: ${{ secrets.GH_PAT }}"
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update snake animation"
          git push